### ISSUE TITLE
Adapt the mesh to a level set

### ISSUE THREAD

**Issue by salazardetroya** [jwallwork23/pyroteus#14]
Hi Joe, this looks pretty cool! Adaptive mesh refinement in Firedrake is such a useful feature. I wonder if one could adapt the mesh to a level set of a scalar function. Something like moving the coordinates of the mesh so the level set coincides with the mesh elements facets and there are no cells cut by the level set. Also, does it work in 3D? How scalable will it be? Thanks.

**Comment by jwallwork23** [comment]
Hi Miguel. Thanks!

This mesh adaptation package is work in progress. We are about to start coupling the metric-based mesh adaptation tool Mmg to PETSc, which will provide h-adaptive mesh adaptation functionality to Firedrake. Once that is complete, it will work in 3D and in parallel. As it stands, this package is mainly providing the functionality to solve an adjoint problem on a sequence of meshes, to facilitate goal-oriented mesh adaptation.

For your application, I think we might be able to do this in pure Firedrake using r-adaptation. I have done that in tidal applications before, with the mesh coordinates moving to track the wet-dry interface. I don't think I can guarantee that cells wouldn't be slightly cut by the level set, but the increased refinement around it would certainly help. Does that sound like what you are looking for?

**Comment by salazardetroya** [comment]
Mmg in PETSc would be pretty neat! As for the r-adaptation, I think that could work. I imagine that just moving the coordinates will eventually cause some ill-shaped elements. Do you have to address that?

**Comment by jwallwork23** [comment]
Depends on your r-adaptation method. Andrew wrote a [paper ](https://arxiv.org/abs/1612.08077) on mesh movement in Firedrake based on solving the Monge-Ampere equation. That formulation ensures that you don't get mesh tangling (provided you solve Monge-Ampere to a reasonable tol). In my experience you only get badly distorted elements if your initial mesh is too coarse.

There is some code available with that paper (with only minor updates to modern Firedrake required). For wetting and drying stuff I've used a monitor function of the form

``m(x) = \frac{\alpha}{\cosh^2(\beta(\eta(x) - b(x)))},``

where `\alpha,\beta>0` are tunable constants, `b` is the (fixed) bathymetry and `\eta` is the (varying) free surface elevation. The monitor function picks out the wet-dry interface.

**Comment by salazardetroya** [comment]
I will take a look at the paper, thanks!
